### ISSUE TITLE
[FEATURE] count by impact

### ISSUE THREAD

**Issue by FilipSkaug** [IT2901Nordic2024/firmware#14]
**What user story is this feature related to?**
User Story #4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
When lifting the device and putting it down on the same side it should increment the count by one.

**Describe a suggested implentation**
Use impact sensor to detect when the device is being lifted or put down

**Task list**
- [x] Use api or sample to activate and impact sensor and define the treshold 
- [x] Write to console when impact sensor is triggered
- [x] Fuction that increment count on trigger

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Inctement count by moving the device
