### ISSUE TITLE
[FEATURE] Track time

### ISSUE THREAD

**Issue by FilipSkaug** [IT2901Nordic2024/firmware#16]
**What user story is this feature related to?**
User Story: #14 
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
The device should track time activated by rotation, 
when the device moves to a side it should start tracking time, and stop tracking time and send it 
when its moved back to the default side

**Describe a suggested implentation**
Use get side function to detect the side change to start tracking the time
when side chages back to the default side send the time and revet the timer to 0

**Task list**
- [x] use get side to start timer
- [x] use get side to stop timer
- [x] send timer as payload

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] start time on side change
- [x] stop time on side change
- [x] send timer as payload
