### ISSUE TITLE
[FEATURE] Make sound

### ISSUE THREAD

**Issue by solvhold** [IT2901Nordic2024/firmware#23]
**What user story is this feature related to?**
User Story 23
User Story Title: As a user i want to get feedback in the form of sounds

**What does this feature entail?**
The thingy to make a sound when asked to.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Add buzzer to device tree
- [x] Create a pwm_dt_spec struct
- [x] Add function for making sound

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Thingy makes sound when start tracking, stop tracking and count
