### ISSUE TITLE
[FEATURE] Enable support for external sensor module

### ISSUE THREAD

**Issue by VebjornNyvoll** [IT2901Nordic2024/firmware#4]
**What user stories is this feature related to?**
User Story 4
User Story Title: As a user I want to track a habit using the device exclusively after configuration

**What does this feature entail?**
Adding necessary files and configurations to enable the ext_sensors module from Asset Tracker v2 in our repository.

**Describe a suggested implentation**
Copy the ext_sensors folder from Asset Tracker v2 and figure out the necessary changes to support the module.

**Task list**
- [ ] Add the ext_sensors module files
- [ ] Test whether the module works
- [ ] Change files as needed until compatibility is achieved

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] All module features work as expected
- [ ] Remaining code is still functioning, AWS connection works as before
- [ ] Changes are documented
