### ISSUE TITLE
[FEATURE] Send sensor data in MQTT json payload

### ISSUE THREAD

**Issue by VebjornNyvoll** [IT2901Nordic2024/firmware#5]
**DEPENDENCIES**
Depends on issue #4 as it is needed to access the sensor module. 
Initial tests can be done before this by using the Asset Tracker v2 sample.

**What user story is this feature related to?**
User Story 4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Alter the standard AWS IoT json payload to send some data from the ext_sensors module instead.

**Describe a suggested implentation**
Ideally send accelerometer data, but the impact sensor might be easier for an initial implementation due to the impact event.

**Task list**
- [x] Get sensor data using the external sensor module
- [x] Alter json payload to send the new sensor data

**Acceptance criteria**
- [x] AWS connection still works
- [x] JSON payload sends any kind of sensor data from the sensor module
- [x] Device shadow in AWS is updated with the new sensor data

**Additional context**
If the issue is solved using the impact sensor, the message send event could be changed from every 30 seconds to being sent on impact event instead.
