### ISSUE TITLE
[FEATURE] Send json payload based on sensor event instead of time

### ISSUE THREAD

**Issue by VebjornNyvoll** [IT2901Nordic2024/firmware#6]
**What user story is this feature related to?**
User Story 4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Currently a json payload is sent to AWS every 30 seconds. This feature requires changing the payload to be sent based on a sensor event instead of being sent on a timed basis to more closely emulate the sending of the final product.

**Describe a suggested implentation**
I suggest utilizing the impact sensor event initially as it is most likely the easiest. Eventually we should analyze accelerometer data to figure out which side is pointing up, but impact is probably easiest for initial implementation.

**Task list**
- [x] Access sensor event, for instance impact
- [x] Change json send function to send based on event instead of time

**Acceptance criteria**
- [x] Contents of payload is not modified
- [x] Payload is no longer sent based on time
- [x] Payload is sent based on sensor event
- [x] Code is documented
