### ISSUE TITLE
[FEATURE] Calculate side based on accelerometer values

### ISSUE THREAD

**Issue by VebjornNyvoll** [IT2901Nordic2024/firmware#7]
**DEPENDECIES**
Issue #4 

**What user story is this feature related to?**
User Story 4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Accessing the accelerometer sensor and calculating side from normal vectors and the X, Y and Z values.

**Task list**
- [x] Access accelerometer values using zephyr sample
- [x] Log accelerometer values to serial terminal
- [x] Find thingys normal vectors
- [x] Sample filter for removing noice
- [x] Dot product between acceleration vector and thingys normal vector
- [x] Return the side that has 0 plus delta degrees between acceleration and normal vector

**Acceptance criteria**
- [x] Filter for acceleration values
- [x] Variable storing the side that is up
