### ISSUE TITLE
[FEATURE] Receive config message from backend

### ISSUE THREAD

**Issue by VebjornNyvoll** [IT2901Nordic2024/firmware#9]
**What user story is this feature related to?**
User Story 5, 6
User Story Titles:
As a user I want to chose what kind of habit tracking to use (e.g. counting or time)
As a user i want to be able to add and remove tracked habits on each side of the device 

**What does this feature entail?**
Receive config message from backend and save the data.

**Describe a suggested implentation**
Should subscribe to a MQTT topic to receive config messages and then save the received data.

**Task list**
- [ ] Enable MQTT subscription
- [ ] Establish with backend which topic should be subscribed to
- [ ] Subscribe to config topic
- [ ] Save data from config message

**Acceptance criteria**
- [ ] Config messages are received
- [ ] Data is stored correctly

**Additional context**
This is needed to alter config based on received messages. Asset Tracker v2 has an implementation of this for inspiration.
